/**
 * Measure what was actually recorded, and write the tables the renderer reads.
 *
 * Run straight after `synthesize.py`. It produces two things:
 *
 * * `src/generated/voiceTimings.ts` — for every spoken shot, how long the clip
 *   is and **when each word is said**, taken from the WordBoundary events the
 *   Speech service emitted while it was synthesising.
 * * `src/dynamicScriptTimings.ts` — the long-form ads' shot boundaries, which
 *   are derived from those durations because those ads are paced by their own
 *   audio rather than by a fixed length.
 *
 * ## Why this exists
 *
 * `dynamicScriptTimings.ts` used to be a committed file that nothing
 * regenerated. CI re-recorded every line from the current script on every run
 * (`npm run voice`), and then laid those new recordings out on shot boundaries
 * measured from an older version of the script. Because the shots are laid end
 * to end, a single line that got longer pushed every later shot out of step
 * with its own audio, and the error accumulated down the whole ninety seconds.
 * Editing one word in shot two was enough to desynchronise shots three to
 * thirty, and nothing anywhere failed.
 *
 * So the table is generated from the same recordings the render will mux, in
 * the same CI run, and `preflight` refuses to render if the table describes a
 * line the script no longer contains.
 *
 * The word timings are the other half of the same bug: see the header of
 * `synthesize.py` for why an even spread across a clip can never line up with
 * speech.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { parseFile } from 'music-metadata';

const FPS = 30;

/**
 * Frames of air left after a line before the shot cuts.
 *
 * A shot that ends on the last syllable reads as clipped, and the cut lands on
 * the viewer still finishing the sentence. Two thirds of a second is enough to
 * let the line land without the film losing pace.
 */
const AIR_FRAMES = 20;

const root = process.cwd();
const audioRoot = path.join(root, 'public', 'audio');

const { ALL_SCRIPTS } = await import(
  pathToFileURL(path.join(root, 'src', 'scripts', 'index.ts')).href
);

const clipName = (n) => `shot_${String(n).padStart(2, '0')}`;

/** Every script that has something spoken in it. */
const voiced = ALL_SCRIPTS.filter((s) => !s.noVoice);

const timings = {};
const missing = [];

for (const script of voiced) {
  const dir = path.join(audioRoot, script.id);
  const lines = {};

  for (const shot of script.shots) {
    const base = clipName(shot.n);
    const mp3 = path.join(dir, `${base}.mp3`);
    const wordsFile = path.join(dir, `${base}.words.json`);

    const stat = await fs.stat(mp3).catch(() => null);
    if (!stat) {
      missing.push(`${script.id} ${base}.mp3`);
      continue;
    }

    // The container's own duration, not the last word's end: a clip carries
    // trailing silence, and a shot cut placed on the last syllable clips it.
    const meta = await parseFile(mp3, { duration: true });
    const audioMs = Math.round((meta.format.duration ?? 0) * 1000);

    let words = [];
    const raw = await fs.readFile(wordsFile, 'utf8').catch(() => null);
    if (raw) {
      try {
        words = JSON.parse(raw);
      } catch {
        missing.push(`${script.id} ${base}.words.json is not valid JSON`);
      }
    } else {
      missing.push(`${script.id} ${base}.words.json`);
    }

    lines[shot.n] = { vo: shot.vo ?? '', audioMs, words };
  }

  timings[script.id] = lines;
}

if (missing.length > 0) {
  console.error('\nNothing to measure for:');
  for (const m of missing) console.error(`  - ${m}`);
  console.error(
    '\nRun `npm run voice` first. A caption cannot be synchronised to a clip\n' +
      'that was never recorded, and guessing is what put the ads out of step.\n',
  );
  process.exit(1);
}

/* ------------------------------------------------- the word-timing module */

const generatedDir = path.join(root, 'src', 'generated');
await fs.mkdir(generatedDir, { recursive: true });

const header = `/**
 * GENERATED by scripts/measure-audio.mjs. Do not edit by hand.
 *
 * When each word of each spoken line is actually said, straight from the
 * Speech service's WordBoundary events. \`KineticWordCaption\` and
 * \`ReelHeadline\` read this so a highlighted word is the word being spoken,
 * rather than a word chosen by dividing the clip into equal slices.
 *
 * Regenerated by \`npm run voice\` on every CI run, from the same recordings
 * that render will mux. The copy committed here is the fallback for a local
 * typecheck; it is not what ships.
 */
export interface SpokenWord {
  text: string;
  /** Milliseconds from the start of the clip. */
  startMs: number;
  durationMs: number;
}

export interface SpokenLine {
  /** The line as the script had it when this was recorded. */
  vo: string;
  /** The clip's own length, trailing silence included. */
  audioMs: number;
  words: SpokenWord[];
}

/** Script id -> shot number -> what was recorded for it. */
export const VOICE_TIMINGS: Record<string, Record<number, SpokenLine>> =
`;

await fs.writeFile(
  path.join(generatedDir, 'voiceTimings.ts'),
  `${header}${JSON.stringify(timings, null, 2)};\n`,
);

/* ------------------------------------- the long-form shot boundary table */

const LONGFORM = voiced.filter((s) => s.format !== 'reel');
const table = {};

for (const script of LONGFORM) {
  const shots = [];
  let cursor = 0;
  for (const shot of script.shots) {
    const line = timings[script.id][shot.n];
    const audioFrames = Math.ceil((line.audioMs / 1000) * FPS);
    const shotFrames = audioFrames + AIR_FRAMES;
    shots.push({
      n: shot.n,
      vo: line.vo,
      audioDurationSec: Number((line.audioMs / 1000).toFixed(3)),
      audioFrames,
      shotFrames,
      startFrame: cursor,
      endFrame: cursor + shotFrames,
    });
    cursor += shotFrames;
  }
  table[script.id] = {
    id: script.id,
    title: script.title,
    totalFrames: cursor,
    shots,
  };
}

const dynamicHeader = `// GENERATED by scripts/measure-audio.mjs. Do not edit by hand.
//
// The long-form ads are paced by their own recordings: each shot is as long as
// its line took to say, plus ${AIR_FRAMES} frames of air. This file is the
// measurement, and it is rewritten from the real mp3s on every \`npm run voice\`.
//
// It was once a hand-maintained file that nothing regenerated, which meant new
// recordings were laid out on boundaries measured from an older script. Because
// the shots run end to end, one line that grew pushed every later shot out of
// step with its own audio. \`preflight\` now refuses to render when a row here
// describes a line the script no longer contains.
export interface ShotTiming {
  n: number;
  vo: string;
  audioDurationSec: number;
  audioFrames: number;
  shotFrames: number;
  startFrame: number;
  endFrame: number;
}

export interface ScriptTiming {
  id: string;
  title: string;
  totalFrames: number;
  shots: ShotTiming[];
}

export const DYNAMIC_SCRIPT_TIMINGS: Record<string, ScriptTiming> =
`;

await fs.writeFile(
  path.join(root, 'src', 'dynamicScriptTimings.ts'),
  `${dynamicHeader}${JSON.stringify(table, null, 2)};\n`,
);

const spoken = Object.values(timings).reduce((n, s) => n + Object.keys(s).length, 0);
const wordCount = Object.values(timings).reduce(
  (n, s) => n + Object.values(s).reduce((m, l) => m + l.words.length, 0),
  0,
);
process.stdout.write(
  `measured ${spoken} clips across ${voiced.length} ads, ${wordCount} word boundaries\n`,
);
for (const [id, t] of Object.entries(table)) {
  process.stdout.write(`  ${id}  ${t.totalFrames} frames  (${(t.totalFrames / FPS).toFixed(1)}s)\n`);
}
