/**
 * A shot is 3.0 seconds — 90 frames at 30fps — and an ad is 30 of them.
 *
 * The three ads differ only in this data. The motion engine is shared, so a
 * fix to the camera or the caption safe-zone lands in all three at once, which
 * is the whole reason the timeline is not written out three times.
 */
export const FPS = 30;
export const SHOT_FRAMES = 90;
export const SHOT_COUNT = 30;
export const TOTAL_FRAMES = SHOT_FRAMES * SHOT_COUNT; // 2700 = 90.0s

/**
 * A Reels cut is exactly 60 seconds — 1,800 frames at 30fps.
 *
 * This is a *second* format, not a re-timing of the first. The long-form ads
 * are paced by their own recorded audio (`dynamicScriptTimings.ts` measures
 * every clip and stretches the shot to fit), which is right when the video can
 * be as long as it needs to be and wrong when the platform is the one holding
 * the stopwatch. Instagram trims, and a 60.4-second reel loses its call to
 * action.
 *
 * So a reel declares `frames` on every shot and those frames must add up to
 * exactly this. `npm run preflight` fails if they do not — a reel that is four
 * frames long in the wrong direction is not something to discover in the
 * upload dialog.
 */
export const REEL_FRAMES = 1800; // 60.0s

/**
 * How the camera treats the device during a shot.
 *
 * Every one of these is applied to the *device container*, never to the screen
 * content inside it. Scaling the inner <Img> is what cropped the nav bar and
 * pushed text under the Dynamic Island last time.
 */
export type CameraMove =
  | 'hero'        // gentle floating wide, slight 3D perspective
  | 'push'        // smooth push-in
  | 'pull'        // pull-back reveal
  | 'trackLeft'   // lateral glide
  | 'trackRight'
  | 'glideDown'   // vertical travel down a long screen
  | 'orbit'       // orbital rotation around Y
  | 'macro'       // close on one region, background softens
  | 'settle';     // arrives and gently overshoots to rest

export interface Shot {
  /** 1-30, for readability against the script document. */
  n: number;
  /**
   * Key into the screen registry, or a plate filename. `null` renders the
   * device dark — used only for the cold-open beats.
   */
  screen: string | null;
  camera: CameraMove;
  /** Big kinetic headline. Kept to a few words; it is not the voiceover. */
  text: string;
  /** The spoken line. 7-11 words so it lands in 1.8-2.4s and leaves air. */
  vo: string;
  /**
   * Which vertical slice of a tall screenshot to favour, 0 = top, 1 = bottom.
   * The camera frames the device; this only chooses what the device is
   * currently scrolled to, which is a property of the screen, not the camera.
   */
  focus?: number;
  /** Accent that lights the background mesh and the rim for this shot. */
  accent?: string;
  /**
   * Exactly how long this shot runs, in frames.
   *
   * Only the reels set it. When it is absent the shot is timed from the
   * measured-audio table, which is what the three long-form ads do and must
   * keep doing — setting this on one of them would override the measurement
   * and clip its own voiceover.
   */
  frames?: number;
}

export interface AdScript {
  id: string;
  title: string;
  /** Edge-TTS voice; never a *MultilingualNeural one. */
  voice: string;
  rate: string;
  pitch: string;
  /**
   * `longform` is the 90-second standalone ad: audio-paced shots, karaoke
   * captions, no music bed. `reel` is the 60-second vertical cut: fixed
   * frames, one bold headline per shot in the platform's safe band, and a
   * music bed under everything so the silent cut is still a film.
   *
   * Absent means `longform`, which is what keeps the three shipped ads
   * byte-identical to what they render today.
   */
  format?: 'longform' | 'reel';
  /**
   * Music bed, relative to `public/`. Generated by `scripts/make-beds.py` —
   * see `.agents/video/REEL-RESEARCH.md` for why it is synthesised rather
   * than sourced. Only the reels carry one.
   */
  music?: string;
  shots: Shot[];
}

/**
 * How long a script runs, in frames.
 *
 * A reel is the sum of its declared shots. A long-form ad is whatever its
 * measured audio came to, which lives in the generated timing table and is
 * read by `Root.tsx`, not here.
 */
export const scriptFrames = (script: AdScript): number =>
  script.shots.reduce((total, shot) => total + (shot.frames ?? 0), 0);
