/**
 * GENERATED by scripts/preflight.mjs. Do not edit by hand.
 *
 * Whether the official Google Play badge artwork is present in `public/`.
 *
 * A Remotion composition runs in a browser and cannot ask the filesystem
 * whether a file exists, and a fetch that 404s mid-render leaves a hole in a
 * finished frame. So preflight answers it here before anything renders.
 *
 * The badge is deliberately not committed. Google's guidelines forbid altering
 * its colour, proportions or spacing, so it must be the official artwork from
 * the Play Console badge generator rather than anything redrawn — and the
 * sandbox this is built in cannot reach play.google.com to fetch it. Until the
 * real file is dropped in, `EndCard` prints plain type that cannot be mistaken
 * for a badge.
 *
 * Drop the PNG at `remotion-ad/public/google-play-badge.png` and the next
 * render picks it up. There is nothing else to change.
 */
export const HAS_PLAY_BADGE = false;
