// GENERATED by scripts/measure-audio.mjs. Do not edit by hand.
//
// Where each shot of each long-form ad starts and ends, measured from the
// recordings CI has just made. `Root.tsx` reads it to give a composition its
// length, and falls back to a fixed frame count when a script is not in here.
//
// **The copy committed here is deliberately empty**, for the same reason
// `src/generated/voiceTimings.ts` is. It has to exist so the bundler resolves
// the import; filling it in from a checkout commits measurements of an older
// recording.
//
// That is not hypothetical. This file sat in the repo holding 90 rows whose
// `vo` was a line the scripts no longer contained — every shot of all three
// long-form ads, left behind by a rewrite. Nothing caught it, because the
// three checks around it look at the recordings and the scripts and never at
// this table. `preflight` compares them now.
export interface ShotTiming {
  n: number;
  vo: string;
  audioDurationSec: number;
  audioFrames: number;
  shotFrames: number;
  startFrame: number;
  endFrame: number;
}

export interface ScriptTiming {
  id: string;
  title: string;
  totalFrames: number;
  shots: ShotTiming[];
}

export const DYNAMIC_SCRIPT_TIMINGS: Record<string, ScriptTiming> = {};
