/** Generated by scripts/build-pg-offline-packs.py after rights and answer audits.
 * Files in this manifest are included in BOTH native and Vercel app builds.
 * This list is intentionally empty until a vetted data import exists.
 */
import type { PgOfflinePack } from '../pgLocalBank';
export const GENERATED_PG_PACKS: PgOfflinePack[] = [];
